
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=handshake-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - "/home1/santiago/docker/volumes/elasticsearch/logs:/var/log:rw"
      - "/home1/santiago/docker/volumes/elasticsearch/data:/usr/share/elasticsearch/data:rw"
      - "/home1/santiago/docker/volumes/elasticsearch/config:/usr/share/elasticsearch/config:rw"
    networks:
      - elastic
    ports:
      - 100.86.230.92:9200:9200
      - 100.86.230.92:9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    volumes:
      - "/mnt/tank/docker/volumes/kibana/logs:/var/log:rw"
      - "/mnt/tank/docker/volumes/kibana/kibana:/usr/share/kibana:rw"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    networks:
      - esnet


  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    container_name: kibana
    environment:
      SERVER_NAME: 127.0.0.1
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 100.86.230.92:5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
    restart: "unless-stopped"

networks:
  esnet:
